services:
  redis:
    restart: always

  backend:
    image: christinjohny/servofixo-backend:latest
    restart: always
    environment:
      - NODE_ENV=production
      - FRONTEND_URL=https://servofixo.cloud
    env_file:
      - ./backend/.env 

  frontend:
    image: christinjohny/servofixo-frontend:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro