import { IServiceCategoryRepository } from '../../../domain/repositories/IServiceCategoryRepository';
import { IImageService } from '../../services/IImageService';
import { ServiceCategory } from '../../../domain/entities/ServiceCategory';

interface CreateCategoryRequest {
  name: string;
  description: string;
  imageFile?: { buffer: Buffer; originalName: string; mimeType: string }; // Optional in type, but validated logic
  isActive: boolean;
}

export class CreateCategoryUseCase {
  constructor(
    private readonly categoryRepo: IServiceCategoryRepository,
    private readonly imageService: IImageService
  ) {}

  async execute(request: CreateCategoryRequest): Promise<ServiceCategory> {
    const existing = await this.categoryRepo.findByName(request.name);
    if (existing) {
      throw new Error('Category with this name already exists');
    }

    if (!request.imageFile) {
      throw new Error('Category icon/image is required');
    }

    // 1. Upload Image to S3
    const iconUrl = await this.imageService.uploadImage(
      request.imageFile.buffer,
      request.imageFile.originalName,
      request.imageFile.mimeType
    );

    // 2. Create Entity
    const newCategory = new ServiceCategory(
      '', // ID generated by DB
      request.name,
      request.description,
      iconUrl,
      request.isActive,
      new Date(),
      new Date()
    );

    // 3. Save to DB
    return this.categoryRepo.create(newCategory);
  }
}