export type RecipientType = "TECHNICIAN" | "CUSTOMER" | "ADMIN";

export type NotificationStatus = "UNREAD" | "READ" | "ARCHIVED";

export type NotificationPriority = "LOW" | "MEDIUM" | "HIGH" | "URGENT";

export enum NotificationType {
  SERVICE_REQUEST_APPROVED = "SERVICE_REQUEST_APPROVED",
  SERVICE_REQUEST_REJECTED = "SERVICE_REQUEST_REJECTED",
  
  BANK_UPDATE_APPROVED = "BANK_UPDATE_APPROVED",
  BANK_UPDATE_REJECTED = "BANK_UPDATE_REJECTED",
  PAYMENT_RECEIVED = "PAYMENT_RECEIVED",
  
  ZONE_REQUEST_APPROVED = "ZONE_REQUEST_APPROVED",
  ZONE_REQUEST_REJECTED = "ZONE_REQUEST_REJECTED",
  
  NEW_BOOKING_ALERT = "NEW_BOOKING_ALERT",
  BOOKING_REQUEST = "BOOKING_REQUEST",
  BOOKING_CONFIRMED = "BOOKING_CONFIRMED",
  BOOKING_STATUS_UPDATE = "BOOKING_STATUS_UPDATE",
  BOOKING_FAILED = "BOOKING_FAILED",
  BOOKING_CANCELLED = "BOOKING_CANCELLED",
  
  ADMIN_NEW_BOOKING = 'ADMIN_NEW_BOOKING',
  ADMIN_BOOKING_FAILED = 'ADMIN_BOOKING_FAILED',
  
  ACCOUNT_VERIFIED = "ACCOUNT_VERIFIED",
  ACCOUNT_SUSPENDED = "ACCOUNT_SUSPENDED",

  BOOKING_APPROVAL_REQUEST = 'BOOKING_APPROVAL_REQUEST' ,
  CHARGE_UPDATE = 'CHARGE_UPDATE',
  PAYMENT_REQUEST = "PAYMENT_REQUEST",
  JOB_COMPLETED = "JOB_COMPLETED",
  BOOKING_COMPLETED="BOOKING_COMPLETED",
  ADMIN_STATUS_UPDATE = "ADMIN_STATUS_UPDATE",
}