import { IServiceItemRepository } from '../../../domain/repositories/IServiceItemRepository';
import { IImageService } from '../../services/IImageService';
import { ServiceItem, ServiceSpecification } from '../../../domain/entities/ServiceItem';

interface CreateServiceRequest {
  categoryId: string;
  name: string;
  description: string;
  basePrice: number;
  specifications: ServiceSpecification[];
  imageFiles: { buffer: Buffer; originalName: string; mimeType: string }[]; // ✅ Array of files
  isActive: boolean;
}

export class CreateServiceItemUseCase {
  constructor(
    private readonly serviceRepo: IServiceItemRepository,
    private readonly imageService: IImageService
  ) {}

  async execute(request: CreateServiceRequest): Promise<ServiceItem> {
    // 1. Check for duplicates within the category
    const existing = await this.serviceRepo.findByNameAndCategory(request.name, request.categoryId);
    if (existing) {
      throw new Error(`Service '${request.name}' already exists in this category.`);
    }

    // 2. Upload ALL images to S3 in parallel
    const uploadPromises = request.imageFiles.map(file => 
      this.imageService.uploadImage(file.buffer, file.originalName, file.mimeType)
    );
    
    const imageUrls = await Promise.all(uploadPromises);

    // 3. Create Entity
    const newService = new ServiceItem(
      '', // ID generated by DB
      request.categoryId,
      request.name,
      request.description,
      request.basePrice,
      request.specifications,
      imageUrls,
      request.isActive,
      new Date(),
      new Date()
    );

    return this.serviceRepo.create(newService);
  }
}